version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - rede-gabriel

  nodeapp:
    build:
      context: ./app
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    networks:
      - rede-gabriel
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/postgres

networks:
  rede-gabriel:
