apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdev
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appdev
  template:
    metadata:
      labels:
        app: appdev
    spec:
      containers:
      - name: appdev
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
