apiVersion: v1
kind: Service
metadata:
    labels:
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: CoreDNS
    name: servicehmg
    namespace: hmg
spec:
  selector:
    app: mydeploymenthmg
  ports:
  - port: 8080
    targetPort: 80
  type: ClusterIP
